### ISSUE TITLE
OSError with Python 3.8 (works with 3.6)

### ISSUE THREAD

**Issue by ivica-k** [thombashi/pytablewriter#18] opened 2019-12-02 20:01 UTC
Trying to run the example code for generating the Markdown table raises OSError

```
from pytablewriter import MarkdownTableWriter

writer = MarkdownTableWriter()
writer.table_name = "example_table"
writer.headers = ["int", "float", "str", "bool", "mix", "time"]
writer.value_matrix = [
    [0,   0.1,      "hoge", True,   0,      "2017-01-01 03:04:05+0900"],
    [2,   "-2.23",  "foo",  False,  None,   "2017-12-23 45:01:23+0900"],
    [3,   0,        "bar",  "true",  "inf", "2017-03-03 33:44:55+0900"],
    [-10, -9.9,     "",     "FALSE", "nan", "2017-01-01 00:00:00+0900"],
]

writer.write_table()
```

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 102, in _python_exit
    thread_wakeup.wakeup()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 90, in wakeup
    self._writer.send_bytes(b"")
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
```

As seen in the traceback, I'm running Python 3.8 with `pytablewriter==0.46.1`. I've tried versions back to `0.43.0` and it didn't help.

The example works well with Python 3.6 and `pytablewriter==0.46.1`. My OS is Archlinux.

Will gladly add any more info, feel free to ask.

**Comment by hugovk** [comment] 2019-12-02 20:58
With macOS Mojave, it's fine with Python 3.7.4 and I can also reproduce it with Python 3.8.0, with a bigger traceback:

```
[hugo:/tmp] % python 1.py
# example_table
# example_table
# example_table
# example_table
# example_table
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 262, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 95, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/tmp/1.py", line 13, in <module>
    writer.write_table()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/text/_markdown.py", line 102, in write_table
    self._write_table()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/text/_text_writer.py", line 232, in _write_table
    self._preprocess()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/_table_writer.py", line 1013, in _preprocess
    exitcode = _main(fd, parent_sentinel)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    self._preprocess_table_dp()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/_table_writer.py", line 931, in _preprocess_table_dp
    main_content = runpy.run_path(main_path,
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 262, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 95, in _run_module_code
    self._table_value_dp_matrix = self._dp_extractor.to_dp_matrix(
    _run_code(code, mod_globals, init_globals,
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 486, in to_dp_matrix
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exec(code, run_globals)
  File "/private/tmp/1.py", line 13, in <module>
    exitcode = _main(fd, parent_sentinel)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    writer.write_table()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/text/_markdown.py", line 102, in write_table
    return self.__to_dp_matrix_mt(value_matrix)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 586, in __to_dp_matrix_mt
    self._write_table()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/text/_text_writer.py", line 232, in _write_table
    prepare(preparation_data)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    self._preprocess()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/_table_writer.py", line 1013, in _preprocess
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    future_list = [
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 587, in <listcomp>
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    exitcode = _main(fd, parent_sentinel)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    self._preprocess_table_dp()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/_table_writer.py", line 931, in _preprocess_table_dp
    executor.submit(
    main_content = runpy.run_path(main_path,
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 262, in run_path
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    prepare(preparation_data)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    self._table_value_dp_matrix = self._dp_extractor.to_dp_matrix(
    return _run_module_code(code, init_globals, run_name,
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 95, in _run_module_code
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 486, in to_dp_matrix
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _run_code(code, mod_globals, init_globals,
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
    main_content = runpy.run_path(main_path,
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 262, in run_path
    self._start_queue_management_thread()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    exec(code, run_globals)
  File "/private/tmp/1.py", line 13, in <module>
    return self.__to_dp_matrix_mt(value_matrix)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 586, in __to_dp_matrix_mt
    return _run_module_code(code, init_globals, run_name,
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 95, in _run_module_code
    writer.write_table()
    future_list = [
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 587, in <listcomp>
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/text/_markdown.py", line 102, in write_table
    self._adjust_process_count()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    _run_code(code, mod_globals, init_globals,
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/tmp/1.py", line 13, in <module>
    executor.submit(
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._write_table()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/text/_text_writer.py", line 232, in _write_table
    p.start()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/process.py", line 121, in start
    writer.write_table()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/text/_markdown.py", line 102, in write_table
    self._preprocess()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/_table_writer.py", line 1013, in _preprocess
    self._start_queue_management_thread()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._popen = self._Popen(self)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    self._write_table()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/text/_text_writer.py", line 232, in _write_table
    self._preprocess_table_dp()
    self._adjust_process_count()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/_table_writer.py", line 931, in _preprocess_table_dp
    self._preprocess()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/_table_writer.py", line 1013, in _preprocess
    return Popen(process_obj)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    p.start()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/process.py", line 121, in start
    super().__init__(process_obj)
    self._preprocess_table_dp()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/_table_writer.py", line 931, in _preprocess_table_dp
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._table_value_dp_matrix = self._dp_extractor.to_dp_matrix(
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 486, in to_dp_matrix
    self._popen = self._Popen(self)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return self.__to_dp_matrix_mt(value_matrix)
    self._table_value_dp_matrix = self._dp_extractor.to_dp_matrix(
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 486, in to_dp_matrix
    return Popen(process_obj)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 586, in __to_dp_matrix_mt
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    return self.__to_dp_matrix_mt(value_matrix)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 586, in __to_dp_matrix_mt
    self._launch(process_obj)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    future_list = [
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 587, in <listcomp>
    self._launch(process_obj)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    future_list = [
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 587, in <listcomp>
    executor.submit(
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    executor.submit(
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    _check_not_importing_main()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    self._start_queue_management_thread()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    self._start_queue_management_thread()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    self._adjust_process_count()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    self._adjust_process_count()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/process.py", line 121, in start
    p.start()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    self._popen = self._Popen(self)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    return Popen(process_obj)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    super().__init__(process_obj)
    self._launch(process_obj)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    _check_not_importing_main()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    self._launch(process_obj)
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "1.py", line 13, in <module>
    writer.write_table()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/text/_markdown.py", line 102, in write_table
    self._write_table()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/text/_text_writer.py", line 232, in _write_table
    self._preprocess()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/_table_writer.py", line 1013, in _preprocess
    self._preprocess_table_dp()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pytablewriter/writer/_table_writer.py", line 931, in _preprocess_table_dp
    self._table_value_dp_matrix = self._dp_extractor.to_dp_matrix(
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 486, in to_dp_matrix
    return self.__to_dp_matrix_mt(value_matrix)
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/site-packages/dataproperty/_extractor.py", line 599, in __to_dp_matrix_mt
    col_idx, value_dp_list = future.result()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/hugo/.pyenv/versions/3.8.0/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[hugo:/tmp] 2s 1 % 
```

Perhaps related to https://github.com/thombashi/pytablewriter/issues/14, which was Windows 10 and Python 3.7?

Or could the issue be coming from DataProperty?

**Comment by thombashi** [comment] 2020-01-01 05:57
@ivica-k @hugovk 
Thank you for your report.

It looks like this caused by a lack of `main` guard.
Could you re-execute the following version?

```py
def main():
    from pytablewriter import MarkdownTableWriter

    writer = MarkdownTableWriter()
    writer.table_name = "example_table"
    writer.headers = ["int", "float", "str", "bool", "mix", "time"]
    writer.value_matrix = [
        [0,   0.1,      "hoge", True,   0,      "2017-01-01 03:04:05+0900"],
        [2,   "-2.23",  "foo",  False,  None,   "2017-12-23 45:01:23+0900"],
        [3,   0,        "bar",  "true",  "inf", "2017-03-03 33:44:55+0900"],
        [-10, -9.9,     "",     "FALSE", "nan", "2017-01-01 00:00:00+0900"],
    ]

    writer.write_table()

if __name__ == '__main__':
    main()
```

I can reproduce the issue at macOS w/ Python 3.8 and confirmed that succeed with the above script.
(Can not reproduce at the Archlinux w/ Python 3.8)

**Comment by hugovk** [comment] 2020-01-02 10:27
I confirm it works with the `main` guard. Thank you!

**Comment by thombashi** [comment] 2020-01-03 13:19
@hugovk 
Thank you for confirmation.

@ivica-k 
I had added main guards to examples at documents and README.
I assume the issue is now fixed.

Feel free to reopen if you still have problem.

**Closed by thombashi** 2020-01-03 13:19 UTC

**Comment by thombashi** [comment] 2020-07-28 05:12
In `pytablewriter 0.52.0` or later, no longer need to add main guard to a program if you do not increase `max_worker` value equals or greater than two (defaults to one).

https://github.com/thombashi/pytablewriter/releases/tag/v0.52.0
